services:
  db:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    image: mysql:5.7
    volumes:
      - source: db
        target: /var/lib/mysql
        type: volume
  wp:
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    image: wordpress:latest
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    volumes:
      - source: wp
        target: /var/www/html
        type: volume
version: '3.7'
volumes:
  db: {}
  wp: {}
